apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hospital-ingress
  namespace: hospital-management
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /health
spec:
  ingressClassName: alb 
  rules:
    - http:
        paths:
          # Traffic to /patient goes to Patient Service
          - path: /patients
            pathType: Prefix
            backend:
              service:
                name: patient-ms-service
                port:
                  number: 80
          # Traffic to /appointment goes to Appointment Service
          - path: /appointments
            pathType: Prefix
            backend:
              service:
                name: appt-ms-service
                port:
                  number: 80